# Generated by Django 2.0.4 on 2018-05-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management_app', '0003_watchedlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField()),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_management_app.WatchedList')),
            ],
        ),
    ]
